# Generated by Django 3.2.7 on 2026-01-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refashion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stocktable',
        ),
        migrations.RenameField(
            model_name='regtable',
            old_name='name',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='regtable',
            name='firstname',
            field=models.CharField(default=11, max_length=150),
            preserve_default=False,
        ),
    ]
